### ISSUE TITLE
[Bug]: Is Tab Split View working correctly in 11.17.1?

### ISSUE THREAD

**Issue by guigirl42** [Floorp-Projects/Floorp#1333]
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [ ] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

At the moment i am uncertain if this actually is a new bug in `11.17.1`, or if possibly instead i just might not yet understand how to use the new method for this function after upgrading from 11.16.x this morning. This is what i believe so far.
1. i do not understand the text in https://blog.ablaze.one/4464/2024-08-01/:
>Split view has evolved significantly! It now supports repositioning and supports splitting by tab-to-tab links!

What does _"repositioning"_ mean here? What does _"splitting by tab-to-tab links"_ mean? How do i _do_ these things?

2. In `Settings - Custom Keyboard Shortcuts` the box `Disable Mozilla Firefox's keyboard shortcuts` always reverts to disabled [unticked] after restarts. Down the bottom of the list, my existing shortcut `Split View Actions` - `Open current tab on right in split view` now does nothing. In `11.16` after invoking this command, the next tab i selected would then be tiled / split with the previously-focused tab. Now in `11.17.1`, nothing at all happens. 

3. If i manually select two tabs, right-click, & select `Open in Split View`, both tabs then do appear side by side, & the new icon appears in the address bar that allows me to toggle their arrangement. That's nice, however...

4. ...in https://blog.ablaze.one/4464/2024-08-01/ the picture seems to show three, or maybe four, tabs split side by side. I cannot do this in my `11.17.1`. If i select three or four tabs, then right-click, & select `Open in Split View`, still only two tabs appear side by side. 

5. The Release Notes mention Zen Browser. In my Zen there are different keyboard shortcuts for splitting, but also it _does successfully_ split up to at least six tabs [possibly more]. I thought Floorp might now also do this, but so far, i have not succeeded. 

Are these behaviours _bugs_, or am i simply not using the `Tab Split View` functions correctly in `11.17.1`?[](url)

### Reproduction Steps

See the previous text pls. 

### Expected Behavior

1. The keyboard shortcuts should work.
2. The `Tab Split View` should work for more than only two tabs, as implied in the Release Notes.

### Actual Behavior

1. The keyboard shortcuts for tab splitting do not work.
2. The `Tab Split View` does not work for more than only two tabs.

### Screenshots

N/A. 

### Browser Version

11.17.1

### Operating System

ArchLinux KDEPlasma

**Comment by surapunoyousei** [comment]
Oops, I stand corrected on this one.

**Comment by surapunoyousei** [comment]
I fixed the keyboard shortcuts in 11.17.4 so that they work correctly.

I made some changes to the behavior so that when you use them with a tab on either the left or right side, it will switch to that tab and split view.

**Comment by guigirl42** [comment]
Hi @surapunoyousei Thank you for working on this. Please may i ask; did you test also with _vertical_ tabs? I use vertical, not horizontal. As i described in my previous post, all sorts of weird misbehaviours are happening when i try to use this function.

After i finish dinner, i am going to retest, but this time in a _virgin_ profile, not my _usual_ profile. I will post the results here, later.

**Comment by guigirl42** [comment]
No, i'm afraid that it's no good still.
- when i use the RMB context menu on selected tabs, it seems to mostly work, but still keeps breaking random other tabs [they go blank]
- when i use the keyboard shortcut, frequently non-target tabs become split, & my second target one does not. It seems wildly unpredictable each time.

**Comment by guigirl42** [comment]
Why did you just close it? **The bug remains present**. _Splitting tabs is not working correctly_.
